config/routes.rb
CookbookOnRails::Application.routes.draw do
 
  resources :recipes
  resources :ingredients
  resources :categories

  
  resources :users


  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions

  match 'tagged' => 'recipes#tagged', :as => 'tagged'

  root to: "ingredients#index"
  
end

app/models/ability.rb
class Ability < ActiveRecord::Base
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

   
    can :manage, :all
    

  end

end

app/models/categories_recipe.rb
class CategoriesRecipe < ActiveRecord::Base
  attr_accessible :category_id, :recipe_id

  belongs_to :categories
  belongs_to :recipes
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :recipes
  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name

  has_many :ingredients_recipes
  has_many :recipes, :through => :ingredients_recipes

  validates :name, presence: true
  

  def cost
    20
    # @cost ||=(rand*100).round(2)
  end

end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base
  attr_accessible :ingredient_id, :recipe_id, :quantity, :ingredient_attributes

  belongs_to :ingredient
  belongs_to :recipe
  accepts_nested_attributes_for :ingredient


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, :instructions, :name, :category_id, :ingredients_recipes_attributes, :tag_list

  acts_as_taggable_on :tags

  belongs_to :category

  has_many :ingredients_recipes
  has_many :ingredients, through: :ingredients_recipes
  

  accepts_nested_attributes_for :ingredients_recipes, allow_destroy: true


  validates :name, presence: true
  validates :name, length: {in: 2..20}
  validate :validate_at_least_one_ingredient
 
  private
  def validate_at_least_one_ingredient
    errors.add(:base, 'needs at least one ingredient') unless ingredients_recipes.size > 0
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates :password, presence: true, on: :create

  validates :email, presence: true

  validates :email, uniqueness: true



  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "get stuffed, hackerzzzz"
  end


  helper_method :current_user

  before_filter :setup_search_object
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private
  def setup_search_object

    @q = Recipe.search(params[:q])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def index
    @categories = Category.all
  end

def show
  @category = Category.find(params[:id])
 
end  

def new
  @category = Category.new
end  


def create
  @category.create(params[:category])
  if @category.save
      redirect_to @category, :notice => "Successfully created category."
    else
      render :action => 'new'
    end
end

def edit
  @category = Category.find(params[:id])
end 

def destroy
  @category = Category.find(params[:id])
  @category.destroy
  
  redirect_to(categories_path)
  end

def update

  @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category, :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
end








end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

def index
    @ingredients = Ingredient.all
  end

def show
  @ingredient = Ingredient.find(params[:id])
  
end  

def new
  @ingredient = Ingredient.new
end  


def create
  Ingredient.create(params[:ingredient])

  redirect_to ingredients_path

end

def edit
  @ingredient = Ingredient.find(params[:id])
end 

def destroy
  @ingredient = Ingredient.find(params[:id])
  @ingredient.destroy
  
  redirect_to(ingredients_path)
  end

def update

  @ingredient = Ingredient.find(params[:id])
  @ingredient.update_attributes(params[:ingredient])
  
  redirect_to(ingredients_path)
end












end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

def index
  @q = Recipe.search(params[:q])

  @recipes = @q.result
end


def show
  @recipe = Recipe.find(params[:id])
end  

def new
  @recipe = Recipe.new
    Ingredient.all.each do |ingredient|
      @recipe.ingredients_recipes.build(ingredient_id: ingredient.id)
    end
end  


def create
  @recipe = Recipe.new(params[:recipe])
    #TODO: Find out why empty quantities are still getting saved on create
    if ir = params[:recipe][:ingredients_recipes_attributes]
      ir.delete_if do |key, value|
        ir[key]['quantity'].blank?
      end
    end

    if @recipe.save
      redirect_to @recipe, :notice => "Successfully created recipe."
    else
      Ingredient.all.each do |ingredient|
        @recipe.ingredients_recipes.build(ingredient_id: ingredient.id)  unless @recipe.ingredients.include?(ingredient)
      end
      render :action => 'new'
    end
end

def edit
  @recipe = Recipe.find(params[:id])
  Ingredient.all.each do |ingredient|
      @recipe.ingredients_recipes.build(ingredient_id: ingredient.id) unless @recipe.ingredients.include?(ingredient)
    end
end 

def destroy
  @recipe = Recipe.find(params[:id])
  @recipe.destroy
  
  redirect_to(recipes_path)
  end

def update
  @recipe = Recipe.find(params[:id])

    if ir = params[:recipe][:ingredients_recipes_attributes]
      ir.keys.each do |key|
        ir[key]['_destroy'] = true if ir[key]['quantity'].blank?
      end
    end

    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe, :notice  => "Successfully updated recipe."
    else
      Ingredient.all.each do |ingredient|
        @recipe.ingredients_recipes.build(ingredient_id: ingredient.id) unless @recipe.ingredients.include?(ingredient)
      end
      render :action => 'edit'
    end
end

def tagged
  if params[:tag].present? 
    @recipes = Recipe.tagged_with(params[:tag])
  else 
    @recipes = Recipe.post.all
  end  
end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

     def create

        user = User.find_by_email(params[:email])

        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to root_url, :notice => "Logged in!"
        else
          flash.now.alert = "Invalid email or password"
          render "new"
        end
      end

      def destroy
        session[:user_id] = nil
        redirect_to root_url, :notice => "Logged out!"
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def create
    if @user.save
      session[:user_id] = @user.id unless current_user
      redirect_to users_path, notice: "Signed up!"
    else
      render "new"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

include ActsAsTaggableOn::TagsHelper

def total_cost(recipe)
  prices = recipe.ingredients.map(&:cost)
  dollar_total = prices.sum.round(2)

  pound_total = (dollar_total / 1.49).round(2)



  "#{number_to_currency(dollar_total)} or #{number_to_currency(pound_total, unit: '£')}"

 end





  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="container2">
  <h2><%=link_to category.name, category_path(category.id)%></h2>
  <%= link_to 'delete', category_path(category.id), method: :delete, confirm: 'Are you sure?'%>
  <%= link_to 'edit', edit_category_path(category.id)%>
</div>

app/views/categories/_form_category.html.erb
<%= form_for @category do |f|%>

    <%= f.label :name%>
    <%= f.text_field :name%> <br>

    <%= f.submit "Submit" %>



<%end%>

app/views/categories/edit.html.erb
<div class="container2">

  <h2>Edit Category</h2>

  <%= render 'form_category' %>

  <%= link_to 'Back', categories_path %>

</div> 

app/views/categories/index.html.erb
<h2>Category Index</h2>

<table>
  <%= render @categories %>
</table>

<h3><%= link_to 'Add Category', new_category_path %></h3>

app/views/categories/new.html.erb
<div class="container2"> 

  <h2>New Category</h2>

  <%= render 'form_category' %>

  <%= link_to 'Back', categories_path %>

</div>

app/views/categories/show.html.erb
<h2>Category Details</h2>

<div class="container2"> 

  <h2>
    <%= @category.name %>
  </h2>


  <h3>Recipes:</h3>
  <%if @category_recipes%>
    <%@category_recipes.each do |recipe| %>
      <%= link_to recipe[0],recipe_path(recipe[1])%><br>

          
              
      
    <%end%>
  <%end%>  

  

</div>  

app/views/ingredients/_form_ingredient.html.erb
<%= form_for @ingredient do |f|%>

    <%= f.label :name%>
    <%= f.text_field :name%> <br>

    <%= f.submit "Submit" %>



<%end%>

app/views/ingredients/_ingredient.html.erb
<div class="container2">
  <h2><%=link_to ingredient.name, ingredient_path(ingredient.id)%></h2>
  <%= link_to 'delete', ingredient_path(ingredient.id), method: :delete, confirm: 'Are you sure?'%>
  <%= link_to 'edit', edit_ingredient_path(ingredient.id)%>
</div>

app/views/ingredients/edit.html.erb
<div class="container2">

  <h2>Edit Ingredient</h2>

  <%= render 'form_ingredient' %>

  <%= link_to 'Back', ingredients_path %>

</div> 

app/views/ingredients/index.html.erb
<h2>Ingredient Index</h2>
<table>
  <%= render @ingredients %>
</table>

<h3><%= link_to 'Add Ingredient', new_ingredient_path %></h3>

app/views/ingredients/new.html.erb
<div class="container2"> 

  <h2>New Ingredient</h2>

  <%= render 'form_ingredient' %>

  <%= link_to 'Back', ingredients_path %>

</div>

app/views/ingredients/show.html.erb
<h2>Ingredient Details</h2>

<div class="container2"> 

  <h2>
    <%= @ingredient.name %>
  </h2>

  

 
  <h3>Recipes:</h3>
  <% @ingredient.ingredients_recipes.each do |ingredients_recipe| %>
    <%= ingredients_recipe.quantity %> on <%= ingredients_recipe.recipe.try(:name) %><br>
  <% end %>

  

</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <header>
    <h1>Cookbook y'all!</h1>

    <% if current_user %>
      <p> <%=current_user.email%></p>
      <%= link_to 'logout', logout_path %>
    <%else%>
      <%= link_to 'login!', login_path %> 
    <%end%>

    <h3>quick search</h3>
    <%= search_form_for @q do |f| %>
        <p>
          <%= f.label :name_cont, "Recipe name contains" %>
          <%= f.text_field :name_cont %>
        </p>
        <p>
          <%= f.submit %>
        </p>
    <% end %>

    <% flash.each do |name, msg| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= msg %>
    </div>
    <% end %>

    

    <nav>
        <ul>
          <li><%= link_to 'Recipes', recipes_path %></li>
                
          <li><%= link_to 'Ingredients', ingredients_path %></li>

          <li><%= link_to 'Categories', categories_path %></li>
                 
        </ul>
    </nav>
  </header>  

<%= yield %>
</div>

</body>
</html>

app/views/recipes/_form_recipe.html.erb
<%= form_for @recipe do |f|%>

  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved, you are an idiot:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name%>
    <%= f.text_field :name%> <br>
    <%= f.label :description%>
    <%= f.text_field :description%> <br>
    <%= f.label :instructions%>
    <%= f.text_field :instructions%> <br>
    
    <%= f.fields_for :ingredients_recipes do |i| %>
    <div class="field">
      <%= i.hidden_field :ingredient_id %>
      <%= i.text_field :quantity %>
      <%= i.label :quantity, "Quantity of #{i.object.ingredient.name}" %>
    </div>
  <% end %>

    <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>

  <p>
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </p>

    
    
    <%= f.submit "Submit" %>



  <%end%>

app/views/recipes/_recipe.html.erb
<div class="container2">
  <h2><%=link_to recipe.name, recipe_path(recipe.id)%></h2>
  <%= link_to 'delete', recipe_path(recipe.id), method: :delete, confirm: 'Are you sure?'%>
  <%= link_to 'edit', edit_recipe_path(recipe.id)%>
   <p>Tags: <%= recipe.tag_list %></p>

   <p>Tags: <% recipe.tag_list.map do |t|%>
   <%= link_to t, tagged_url(:tag => t) %>
   <%end%>

 </p>
</div>

app/views/recipes/edit.html.erb
<div class="container2">

  <h2>Edit Recipe</h2>

  <%= render 'form_recipe' %>

  <%= link_to 'Back', recipes_path %>

</div>  

app/views/recipes/index.html.erb
<h3>Recipe Search</h3>

<%= search_form_for @q do |f| %>
  <p>
    <%= f.label :name_cont, "Recipe name contains" %>
    <%= f.text_field :name_cont %>
  </p>
  <p>
    <%= f.label :category_name_cont, "Category name contains" %>
    <%= f.text_field :category_name_cont %>
  </p>
  <p>
    <%= f.label :ingredients_name_cont, "Ingredient name contains" %>
    <%= f.text_field :ingredients_name_cont %>
  </p>



  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2>Recipe Index</h2>
<table>
  <%= render @recipes %>
</table>

<div id="tag_cloud">
  <% tag_cloud Recipe.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name), class: css_class %>
  <% end %>
</div>

<h3><%= link_to 'Add Recipe', new_recipe_path %></h3>

app/views/recipes/new.html.erb
<div class="container2"> 

  <h2>New Recipe</h2>

  <%= render 'form_recipe' %>

  <%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/show.html.erb
<h2>Recipe Details</h2>

<div class="container2"> 

  <h2>
    <%= @recipe.name %><br>
  </h2>

  <h3><%= @recipe.description %><br></h3>
  <%= @recipe.instructions %><br>

  <p>Ingredients:</p>
  <% @recipe.ingredients_recipes.each do |ingredients_recipe| %>
    <%= ingredients_recipe.quantity %> of <%= ingredients_recipe.ingredient.try(:name) %><br>
  <% end %>



  <p>Categories:</p>
  <%= @recipe.category.try(:name) %>

  <p>Total Cost:</p>
  <%= total_cost(@recipe) %>

  <p>Tags:</p>
  <% @recipe.tags.any? %>
  <% @recipe.tags.each do |tag| %>
  <%= link_to tag.name, tagged_url(tag: tag.name) %>
<% end %>

</div>  

app/views/recipes/tagged.html.erb
<h2>Tag Results</h2>

<table>
  <%= render @recipes %>
</table>

app/views/users/create.html.erb
<h1>Users#create</h1>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user| %>
<%= user.email %>
<%= user.password_digest %>
<br>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      
      <div class="actions"><%= f.submit %></div>
    <% end %>